// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: insurance.proto

package insurance.grpc;

/**
 * Protobuf type {@code CoverageRequest}
 */
public final class CoverageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CoverageRequest)
    CoverageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CoverageRequest.newBuilder() to construct.
  private CoverageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CoverageRequest() {
    insuranceId_ = "";
    medicalAct_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CoverageRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return insurance.grpc.InsuranceProto.internal_static_CoverageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return insurance.grpc.InsuranceProto.internal_static_CoverageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            insurance.grpc.CoverageRequest.class, insurance.grpc.CoverageRequest.Builder.class);
  }

  public static final int INSURANCEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object insuranceId_ = "";
  /**
   * <code>string insuranceId = 1;</code>
   * @return The insuranceId.
   */
  @java.lang.Override
  public java.lang.String getInsuranceId() {
    java.lang.Object ref = insuranceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      insuranceId_ = s;
      return s;
    }
  }
  /**
   * <code>string insuranceId = 1;</code>
   * @return The bytes for insuranceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInsuranceIdBytes() {
    java.lang.Object ref = insuranceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      insuranceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDICALACT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object medicalAct_ = "";
  /**
   * <code>string medicalAct = 2;</code>
   * @return The medicalAct.
   */
  @java.lang.Override
  public java.lang.String getMedicalAct() {
    java.lang.Object ref = medicalAct_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      medicalAct_ = s;
      return s;
    }
  }
  /**
   * <code>string medicalAct = 2;</code>
   * @return The bytes for medicalAct.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMedicalActBytes() {
    java.lang.Object ref = medicalAct_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      medicalAct_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ESTIMATEDCOST_FIELD_NUMBER = 3;
  private double estimatedCost_ = 0D;
  /**
   * <code>double estimatedCost = 3;</code>
   * @return The estimatedCost.
   */
  @java.lang.Override
  public double getEstimatedCost() {
    return estimatedCost_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(insuranceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, insuranceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(medicalAct_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, medicalAct_);
    }
    if (java.lang.Double.doubleToRawLongBits(estimatedCost_) != 0) {
      output.writeDouble(3, estimatedCost_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(insuranceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, insuranceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(medicalAct_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, medicalAct_);
    }
    if (java.lang.Double.doubleToRawLongBits(estimatedCost_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, estimatedCost_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof insurance.grpc.CoverageRequest)) {
      return super.equals(obj);
    }
    insurance.grpc.CoverageRequest other = (insurance.grpc.CoverageRequest) obj;

    if (!getInsuranceId()
        .equals(other.getInsuranceId())) return false;
    if (!getMedicalAct()
        .equals(other.getMedicalAct())) return false;
    if (java.lang.Double.doubleToLongBits(getEstimatedCost())
        != java.lang.Double.doubleToLongBits(
            other.getEstimatedCost())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INSURANCEID_FIELD_NUMBER;
    hash = (53 * hash) + getInsuranceId().hashCode();
    hash = (37 * hash) + MEDICALACT_FIELD_NUMBER;
    hash = (53 * hash) + getMedicalAct().hashCode();
    hash = (37 * hash) + ESTIMATEDCOST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getEstimatedCost()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static insurance.grpc.CoverageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static insurance.grpc.CoverageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static insurance.grpc.CoverageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static insurance.grpc.CoverageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static insurance.grpc.CoverageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static insurance.grpc.CoverageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(insurance.grpc.CoverageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CoverageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CoverageRequest)
      insurance.grpc.CoverageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return insurance.grpc.InsuranceProto.internal_static_CoverageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return insurance.grpc.InsuranceProto.internal_static_CoverageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              insurance.grpc.CoverageRequest.class, insurance.grpc.CoverageRequest.Builder.class);
    }

    // Construct using insurance.grpc.CoverageRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      insuranceId_ = "";
      medicalAct_ = "";
      estimatedCost_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return insurance.grpc.InsuranceProto.internal_static_CoverageRequest_descriptor;
    }

    @java.lang.Override
    public insurance.grpc.CoverageRequest getDefaultInstanceForType() {
      return insurance.grpc.CoverageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public insurance.grpc.CoverageRequest build() {
      insurance.grpc.CoverageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public insurance.grpc.CoverageRequest buildPartial() {
      insurance.grpc.CoverageRequest result = new insurance.grpc.CoverageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(insurance.grpc.CoverageRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.insuranceId_ = insuranceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.medicalAct_ = medicalAct_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.estimatedCost_ = estimatedCost_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof insurance.grpc.CoverageRequest) {
        return mergeFrom((insurance.grpc.CoverageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(insurance.grpc.CoverageRequest other) {
      if (other == insurance.grpc.CoverageRequest.getDefaultInstance()) return this;
      if (!other.getInsuranceId().isEmpty()) {
        insuranceId_ = other.insuranceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMedicalAct().isEmpty()) {
        medicalAct_ = other.medicalAct_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getEstimatedCost() != 0D) {
        setEstimatedCost(other.getEstimatedCost());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              insuranceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              medicalAct_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              estimatedCost_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object insuranceId_ = "";
    /**
     * <code>string insuranceId = 1;</code>
     * @return The insuranceId.
     */
    public java.lang.String getInsuranceId() {
      java.lang.Object ref = insuranceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        insuranceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string insuranceId = 1;</code>
     * @return The bytes for insuranceId.
     */
    public com.google.protobuf.ByteString
        getInsuranceIdBytes() {
      java.lang.Object ref = insuranceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        insuranceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string insuranceId = 1;</code>
     * @param value The insuranceId to set.
     * @return This builder for chaining.
     */
    public Builder setInsuranceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      insuranceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string insuranceId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInsuranceId() {
      insuranceId_ = getDefaultInstance().getInsuranceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string insuranceId = 1;</code>
     * @param value The bytes for insuranceId to set.
     * @return This builder for chaining.
     */
    public Builder setInsuranceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      insuranceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object medicalAct_ = "";
    /**
     * <code>string medicalAct = 2;</code>
     * @return The medicalAct.
     */
    public java.lang.String getMedicalAct() {
      java.lang.Object ref = medicalAct_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicalAct_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string medicalAct = 2;</code>
     * @return The bytes for medicalAct.
     */
    public com.google.protobuf.ByteString
        getMedicalActBytes() {
      java.lang.Object ref = medicalAct_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicalAct_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string medicalAct = 2;</code>
     * @param value The medicalAct to set.
     * @return This builder for chaining.
     */
    public Builder setMedicalAct(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      medicalAct_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string medicalAct = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMedicalAct() {
      medicalAct_ = getDefaultInstance().getMedicalAct();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string medicalAct = 2;</code>
     * @param value The bytes for medicalAct to set.
     * @return This builder for chaining.
     */
    public Builder setMedicalActBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      medicalAct_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double estimatedCost_ ;
    /**
     * <code>double estimatedCost = 3;</code>
     * @return The estimatedCost.
     */
    @java.lang.Override
    public double getEstimatedCost() {
      return estimatedCost_;
    }
    /**
     * <code>double estimatedCost = 3;</code>
     * @param value The estimatedCost to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedCost(double value) {

      estimatedCost_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double estimatedCost = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEstimatedCost() {
      bitField0_ = (bitField0_ & ~0x00000004);
      estimatedCost_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CoverageRequest)
  }

  // @@protoc_insertion_point(class_scope:CoverageRequest)
  private static final insurance.grpc.CoverageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new insurance.grpc.CoverageRequest();
  }

  public static insurance.grpc.CoverageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CoverageRequest>
      PARSER = new com.google.protobuf.AbstractParser<CoverageRequest>() {
    @java.lang.Override
    public CoverageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CoverageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CoverageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public insurance.grpc.CoverageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

