// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: insurance.proto

package insurance.grpc;

public interface CoverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CoverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool validPolicy = 1;</code>
   * @return The validPolicy.
   */
  boolean getValidPolicy();

  /**
   * <code>bool covered = 2;</code>
   * @return The covered.
   */
  boolean getCovered();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
