// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: insurance.proto

package insurance.grpc;

public final class InsuranceProto {
  private InsuranceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CoverageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CoverageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CoverageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CoverageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017insurance.proto\"Q\n\017CoverageRequest\022\023\n\013" +
      "insuranceId\030\001 \001(\t\022\022\n\nmedicalAct\030\002 \001(\t\022\025\n" +
      "\restimatedCost\030\003 \001(\001\"I\n\020CoverageResponse" +
      "\022\023\n\013validPolicy\030\001 \001(\010\022\017\n\007covered\030\002 \001(\010\022\017" +
      "\n\007message\030\003 \001(\t2H\n\020InsuranceService\0224\n\rC" +
      "heckCoverage\022\020.CoverageRequest\032\021.Coverag" +
      "eResponseB\"\n\016insurance.grpcB\016InsurancePr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CoverageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CoverageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CoverageRequest_descriptor,
        new java.lang.String[] { "InsuranceId", "MedicalAct", "EstimatedCost", });
    internal_static_CoverageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CoverageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CoverageResponse_descriptor,
        new java.lang.String[] { "ValidPolicy", "Covered", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
