// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: insurance.proto

package insurance.grpc;

public interface CoverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CoverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string insuranceId = 1;</code>
   * @return The insuranceId.
   */
  java.lang.String getInsuranceId();
  /**
   * <code>string insuranceId = 1;</code>
   * @return The bytes for insuranceId.
   */
  com.google.protobuf.ByteString
      getInsuranceIdBytes();

  /**
   * <code>string medicalAct = 2;</code>
   * @return The medicalAct.
   */
  java.lang.String getMedicalAct();
  /**
   * <code>string medicalAct = 2;</code>
   * @return The bytes for medicalAct.
   */
  com.google.protobuf.ByteString
      getMedicalActBytes();

  /**
   * <code>double estimatedCost = 3;</code>
   * @return The estimatedCost.
   */
  double getEstimatedCost();
}
