package orchestrator.model;

public enum RequestStatus {
    SUBMITTED,
    IDENTITY_VERIFIED, IDENTITY_FAILED,
    INSURANCE_VALIDATED, INSURANCE_REJECTED,
    RISK_SCORED, RULES_REJECTED,
    DOCS_VALIDATED, DOCS_MISSING,
    EXPERT_APPROVED, EXPERT_REJECTED,
    COST_CALCULATED,
    FIN_AUTHORIZED, FIN_REJECTED,
    COMPLETED_APPROVED, COMPLETED_REJECTED,
    ERROR_EXTERNAL_SERVICE
}