
package orchestrator.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentityWebServiceService", targetNamespace = "http://soap.identity/", wsdlLocation = "http://localhost:8082/identity?wsdl")
public class IdentityWebServiceService
    extends Service
{

    private final static URL IDENTITYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IDENTITYWEBSERVICESERVICE_EXCEPTION;
    private final static QName IDENTITYWEBSERVICESERVICE_QNAME = new QName("http://soap.identity/", "IdentityWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/identity?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTITYWEBSERVICESERVICE_WSDL_LOCATION = url;
        IDENTITYWEBSERVICESERVICE_EXCEPTION = e;
    }

    public IdentityWebServiceService() {
        super(__getWsdlLocation(), IDENTITYWEBSERVICESERVICE_QNAME);
    }

    public IdentityWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTITYWEBSERVICESERVICE_QNAME, features);
    }

    public IdentityWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, IDENTITYWEBSERVICESERVICE_QNAME);
    }

    public IdentityWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTITYWEBSERVICESERVICE_QNAME, features);
    }

    public IdentityWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentityWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdentityWebService
     */
    @WebEndpoint(name = "IdentityWebServicePort")
    public IdentityWebService getIdentityWebServicePort() {
        return super.getPort(new QName("http://soap.identity/", "IdentityWebServicePort"), IdentityWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentityWebService
     */
    @WebEndpoint(name = "IdentityWebServicePort")
    public IdentityWebService getIdentityWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.identity/", "IdentityWebServicePort"), IdentityWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTITYWEBSERVICESERVICE_EXCEPTION!= null) {
            throw IDENTITYWEBSERVICESERVICE_EXCEPTION;
        }
        return IDENTITYWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
