
package orchestrator.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IdentityWebService", targetNamespace = "http://soap.identity/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdentityWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyIdentity", targetNamespace = "http://soap.identity/", className = "orchestrator.soap.client.VerifyIdentity")
    @ResponseWrapper(localName = "verifyIdentityResponse", targetNamespace = "http://soap.identity/", className = "orchestrator.soap.client.VerifyIdentityResponse")
    @Action(input = "http://soap.identity/IdentityWebService/verifyIdentityRequest", output = "http://soap.identity/IdentityWebService/verifyIdentityResponse")
    public boolean verifyIdentity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
